services:
  web:
    build: ./backend
    restart: unless-stopped
    depends_on:
      mydb:
        condition: service_healthy
    ports:
      - "8069:8069"
    volumes:
      - ./backend/odoo/addons:/mnt/extra-addons
      - ./backend/odoo/odoo.conf:/etc/odoo/odoo.conf
      - ./backend/data/odoo:/var/lib/odoo
    environment:
      - HOST=mydb
      - USER=odoo
      - PASSWORD=myodoo
      - DB_HOST=mydb
      - DB_PORT=5432
      - DB_USER=odoo
      - DB_PASSWORD=myodoo
    env_file:
      - ./backend/.env
    command:
      - odoo
      - -c
      - /etc/odoo/odoo.conf
      - --load=web
      - --log-level
      - info
    networks:
      - condome_net

  mydb:
    image: postgres:15
    restart: unless-stopped
    stop_grace_period: 60s
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=myodoo
      - POSTGRES_USER=odoo
    volumes:
      - ./backend/data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo -d postgres || exit 1"]
      start_period: 120s
      interval: 10s
      timeout: 5s
      retries: 20
    networks:
      - condome_net

  mailhog:
    image: mailhog/mailhog
    restart: unless-stopped
    ports:
      - "1025:1025" # Puerto SMTP
      - "8025:8025" # Interfaz Web para ver correos
    networks:
      - condome_net

networks:
  condome_net:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_ip_masquerade: "true"
