{
    "name": "Condome API",
    "version": "1.0.0",
    "summary": "Gateway de compatibilidad para la API de Condome",
    "description": "Mantiene el namespace /condome_api mientras la lógica vive en addons más pequeños.",
    "category": "Custom",
    "depends": [
        "base",
        "condome_auth",
        "condome_core",
        "condome_structure",
        "condome_directory",
        "condome_people",
        "condome_access_control",
        "condome_incident",
        "condome_governance",
        "condome_reservation",
        "condome_dashboard",
        "condome_roles",
        "condome_billing",
        "condome_reporting",
        "condome_mail",
    ],
    "installable": True,
    "application": False,
    "license": "LGPL-3",
}
